version: '3.1'
name: ipg-docker-webserver

services:
  webserver:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      - DB_HOST=database

  database:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
